name: BossEncounters
version: 0.1.0
main: com.orangeslices.bossencounters.BossEncountersPlugin
api-version: '1.21'
author: OrangeSlices
description: Rare boss-like encounters with minimal lag (event-driven).

commands:
  bec:
    description: BossEncounters admin commands
    usage: /bec <makeboss|unboss|debug>
    permission: bossencounters.admin

permissions:
  bossencounters.admin:
    default: op
